<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\GeneratedArtifact;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use League\CommonMark\GithubFlavoredMarkdownConverter;
use Symfony\Component\HttpFoundation\Response;

/**
 * Saved AI generator artifacts (KPI / IDP / Report), scoped per user so history
 * follows the account across devices.
 */
class ArtifactController extends Controller
{
    public function index(Request $request): JsonResponse
    {
        $items = GeneratedArtifact::where('user_id', $request->user()->id)
            ->orderByDesc('created_at')
            ->get()
            ->map(fn ($a) => $this->summary($a));

        return response()->json(['data' => $items]);
    }

    public function store(Request $request): JsonResponse
    {
        $data = $request->validate([
            'kind' => ['required', 'in:kpi,idp,report'],
            'title' => ['required', 'string', 'max:160'],
            'markdown' => ['required', 'string', 'max:20000'],
            'source' => ['nullable', 'in:claude,rules,stopped'],
            'params' => ['nullable', 'array'],
        ]);
        $data['user_id'] = $request->user()->id;

        $artifact = GeneratedArtifact::create($data);

        return response()->json(['data' => $this->full($artifact)], 201);
    }

    public function show(Request $request, int $id): JsonResponse
    {
        $artifact = GeneratedArtifact::where('user_id', $request->user()->id)->findOrFail($id);

        return response()->json(['data' => $this->full($artifact)]);
    }

    public function destroy(Request $request, int $id): JsonResponse
    {
        $artifact = GeneratedArtifact::where('user_id', $request->user()->id)->findOrFail($id);
        $artifact->delete();

        return response()->json(['data' => ['id' => $id]]);
    }

    /** Render a Markdown artifact to a downloadable PDF. */
    public function pdf(Request $request): Response
    {
        $data = $request->validate([
            'title' => ['required', 'string', 'max:160'],
            'markdown' => ['required', 'string', 'max:20000'],
        ]);

        $body = (string) (new GithubFlavoredMarkdownConverter())->convert($data['markdown']);
        $title = e($data['title']);
        $date = now()->toFormattedDateString();

        $html = <<<HTML
        <!doctype html>
        <html><head><meta charset="utf-8"><style>
          * { font-family: DejaVu Sans, sans-serif; }
          body { color: #1e293b; font-size: 12px; line-height: 1.5; }
          .brand { color: #1d4ed8; font-weight: bold; letter-spacing: .5px; font-size: 11px; }
          .meta { color: #64748b; font-size: 10px; margin-bottom: 16px; }
          h1 { font-size: 20px; color: #0f172a; margin: 8px 0; }
          h2 { font-size: 15px; color: #1d4ed8; margin: 16px 0 6px; }
          h3 { font-size: 13px; margin: 12px 0 4px; }
          table { width: 100%; border-collapse: collapse; margin: 8px 0; }
          th, td { border: 1px solid #cbd5e1; padding: 5px 8px; text-align: left; font-size: 11px; }
          th { background: #f1f5f9; }
          ul, ol { margin: 6px 0 6px 18px; }
          code { background: #f1f5f9; padding: 1px 4px; border-radius: 3px; }
          hr { border: none; border-top: 1px solid #e2e8f0; margin: 12px 0; }
          .footer { color: #94a3b8; font-size: 9px; margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 6px; }
        </style></head><body>
          <div class="brand">NEXUS · Competency &amp; Performance</div>
          <div class="meta">Generated {$date}</div>
          {$body}
          <div class="footer">Generated by NEXUS — {$title}</div>
        </body></html>
        HTML;

        $pdf = Pdf::loadHTML($html)->setPaper('a4');
        $slug = Str::slug($data['title']) ?: 'artifact';

        return $pdf->download("nexus-{$slug}.pdf");
    }

    private function summary(GeneratedArtifact $a): array
    {
        return [
            'id' => $a->id,
            'kind' => $a->kind,
            'title' => $a->title,
            'source' => $a->source,
            'createdAt' => $a->created_at?->toIso8601String(),
        ];
    }

    private function full(GeneratedArtifact $a): array
    {
        return array_merge($this->summary($a), [
            'markdown' => $a->markdown,
            'params' => $a->params,
        ]);
    }
}
